export const architectureStyles = {
  root:         "overflow-y-auto h-full bg-slate-50",
  inner:        "mx-auto max-w-5xl px-6 py-8",
  header:       "mb-7 flex items-start justify-between gap-4",
  headerTitle:  "text-2xl font-bold text-slate-900",
  headerSubtitle: "mt-1.5 text-sm text-slate-500 max-w-2xl",
  cardsWrap:    "flex flex-col lg:flex-row items-stretch gap-5 mb-6",
  card:         "flex-1 border border-slate-200 bg-white p-6 shadow-sm",
  cardIconWrap: "h-9 w-9 rounded-lg bg-slate-50 flex items-center justify-center text-slate-600",
  cardMeta:     "flex items-center gap-3 mb-4",
  cardMetaInner:"",
  cardTypeLabel:"text-[10px] font-semibold uppercase tracking-widest text-slate-400",
  cardTitle:    "text-sm font-semibold text-slate-900 mt-0.5",
  cardBadge:    "ml-auto rounded-full px-2.5 py-0.5 text-[10px] font-semibold",
  cardBadgeDetermined: "bg-emerald-50 text-emerald-700",
  cardBadgeSystem:     "bg-slate-100 text-slate-600",
  cardDesc:     "text-sm text-slate-600",
  divider:      "hidden lg:flex flex-col items-center justify-center px-2 text-slate-300",
  dividerSymbol:"text-xl font-bold",
  cta:          "flex flex-col items-center gap-4",
  ctaBtn:       "bg-indigo-600 hover:bg-indigo-700 text-white shadow-md rounded-xl px-8 py-5 text-sm gap-2",
}
