export const whatIfStyles = {
  root:          "overflow-y-auto h-full bg-slate-50",
  inner:         "mx-auto max-w-7xl px-6 py-8",
  headerLabel:   "text-[10px] font-semibold uppercase tracking-[0.28em] text-slate-400",
  headerTitle:   "mt-2 text-2xl font-bold text-slate-900",
  headerSubtitle:"mt-2 text-sm text-slate-500",
  grid:          "grid grid-cols-1 gap-5 lg:grid-cols-3 mb-6",
  card:          "group flex flex-col border border-t-4 bg-white p-6 shadow-sm transition-all hover:-translate-y-0.5",
  cardSelected:  "ring-2 ring-offset-2 ring-offset-slate-50 ring-slate-900/10",
  badgeWrap:     "inline-flex items-center gap-2 rounded-full bg-slate-50 px-3 py-1 text-xs font-semibold text-slate-700",
  cardHeader:    "flex items-start gap-3",
  iconWrap:      "mt-1 h-9 w-9 shrink-0 rounded-xl bg-slate-50 flex items-center justify-center text-slate-600",
  cardTitle:     "text-base font-semibold leading-snug transition-colors",
  cardPrompt:    "mt-2 text-xs leading-relaxed text-slate-500",
  blocks:        "space-y-3",
  block:         "rounded-xl bg-slate-50 p-3.5",
  blockLabel:    "text-[10px] font-bold uppercase tracking-widest text-slate-400",
  blockText:     "mt-1.5 text-xs leading-relaxed text-slate-600",
  applyBtn:      "h-10 w-full rounded-xl bg-slate-900 text-white hover:bg-slate-800 text-xs gap-2",
  footer:        "flex justify-center",
  standardPath:  "text-xs font-medium text-slate-400 hover:text-slate-700 transition-colors",
}
