export const pitchStyles = {
  root:          "flex flex-col h-full",
  header:        "shrink-0 flex items-center justify-between px-5 py-2.5 border-b border-slate-200 bg-white",
  headerLeft:    "flex items-center gap-3",
  headerTitle:   "text-xs font-semibold text-slate-700",
  tabGroup:      "flex rounded-lg border border-slate-200 p-0.5 bg-slate-50",
  tabActive:     "px-3 py-1 rounded-md text-[11px] font-medium transition-all bg-white shadow-sm text-slate-800",
  tabInactive:   "px-3 py-1 rounded-md text-[11px] font-medium transition-all text-slate-500 hover:text-slate-700",
  body:          "flex-1 flex overflow-hidden",
  stepList:      "w-48 shrink-0 border-r border-slate-200 overflow-y-auto bg-slate-50/60 p-3 flex flex-col gap-1",
  stepBtn:       "flex items-center gap-2.5 rounded-lg px-3 py-2.5 text-left transition-all",
  stepBtnActive: "bg-white shadow-sm border border-slate-200",
  stepBtnInact:  "hover:bg-white/70",
  stepNumActive: "flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[10px] font-bold bg-indigo-600 text-white",
  stepNumDone:   "flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[10px] font-bold bg-slate-300 text-white",
  stepNumPend:   "flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[10px] font-bold border border-slate-300 text-slate-400",
  stepLabel:     "text-[11px] font-medium leading-tight",
  stepLabelAct:  "text-slate-900",
  stepLabelInact:"text-slate-500",
  progress:      "mt-3 px-1",
  progressBar:   "h-1 w-full rounded-full bg-slate-200",
  progressFill:  "h-1 rounded-full bg-indigo-500 transition-all",
  progressText:  "mt-1 text-[9px] text-slate-400 text-center",
  content:       "flex-1 flex flex-col overflow-hidden",
  contentBody:   "flex-1 overflow-y-auto px-8 py-6",
  contentTitle:  "text-lg font-bold text-slate-900 mb-4",
  prose:         "prose prose-sm prose-slate max-w-none",
  footer:        "shrink-0 border-t border-slate-200 bg-white px-6 py-3 flex items-center justify-between",
  footerLabel:   "text-[11px] text-slate-400",
}
