export const scenarioStyles = {
  root:           "overflow-y-auto h-full",
  inner:          "max-w-5xl mx-auto px-6 py-8",
  grid:           "grid grid-cols-1 lg:grid-cols-12 gap-6 mb-6",
  personaCard:    "col-span-1 lg:col-span-4",
  timelineCard:   "col-span-1 lg:col-span-8",
  avatar:         "h-14 w-14 rounded-full bg-slate-100 flex items-center justify-center text-slate-700 text-lg font-semibold",
  personaName:    "text-base font-semibold text-slate-900",
  personaRole:    "text-xs text-slate-500",
  personaDetails: "mt-5 space-y-3",
  labelTag:       "text-[9px] text-slate-400 uppercase tracking-widest mb-1.5",
  roleBadge:      "inline-block rounded-full px-3 py-1 text-xs bg-slate-100 text-slate-700",
  painBadge:      "inline-block rounded-full px-3 py-1 text-xs bg-rose-50 text-rose-700",
  timeline:       "relative",
  timelineLine:   "absolute left-6 top-0 bottom-0 w-px bg-slate-200",
  timelineSteps:  "space-y-7",
  timelineStep:   "flex items-start gap-5",
  timelineIconWrap: "w-12 flex justify-center",
  timelineIcon:   "h-8 w-8 rounded-full border flex items-center justify-center",
  timelineIconNormal: "border-slate-200 bg-white text-slate-600",
  timelineIconHigh:   "border-indigo-200 bg-indigo-50 text-indigo-600",
  timelineContent:"flex-1",
  timelineLabel:  "text-xs text-slate-500 mb-0.5",
  timelineTextNorm: "text-sm font-medium text-slate-800",
  timelineTextHigh: "rounded-lg border border-indigo-100 bg-indigo-50/40 p-3 text-sm text-slate-700",
  metricsTitle:   "text-base font-semibold text-slate-900 text-center mb-5",
  metricsGrid:    "grid grid-cols-2 gap-4 max-w-2xl mx-auto",
  metricBefore:   "p-5 border border-dashed text-center",
  metricBeforeVal:"text-5xl font-bold text-slate-300",
  metricAfter:    "p-5 border border-indigo-200 text-center",
  metricAfterVal: "text-5xl font-bold text-indigo-600",
  metricLabel:    "mt-2 text-xs text-slate-500",
  metricAfterLabel: "mt-2 text-xs text-slate-500 flex items-center justify-center gap-1.5",
}
