export const empathyStyles = {
  root:          "flex flex-col h-full",
  header:        "shrink-0 flex items-center justify-between px-5 py-2.5 border-b border-slate-200 bg-white",
  headerLeft:    "",
  headerTitle:   "text-xs font-semibold text-slate-700",
  headerSubtitle:"text-[10px] text-slate-400 mt-0.5",
  body:          "flex-1 overflow-y-auto p-5",
  topGrid:       "grid grid-cols-2 gap-4 mb-4",
  bottomGrid:    "grid grid-cols-2 gap-4",
  card:          "bg-white border border-slate-200 shadow-sm",
  cardInner:     "p-5",
  cardHeader:    "flex items-center gap-2 mb-4",
  cardTitle:     "text-sm font-semibold text-slate-800",
  cardAddBtn:    "ml-auto rounded-md p-1 text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors",
  emptyState:    "flex items-center justify-center rounded-lg border border-dashed border-slate-200 py-5",
  emptyText:     "text-xs text-slate-400",
  list:          "space-y-2",
  listItem:      "group flex items-start gap-2 rounded-lg bg-slate-50 px-3 py-2.5 cursor-grab active:cursor-grabbing",
  itemText:      "flex-1 text-[12px] leading-snug text-slate-800 cursor-text",
  itemTextarea:  "flex-1 resize-none bg-transparent text-[12px] text-slate-900 focus:outline-none",
  itemDelete:    "shrink-0 mt-0.5 opacity-0 group-hover:opacity-100 transition-opacity text-slate-300 hover:text-rose-500",
  grip:          "h-3.5 w-3.5 mt-0.5 shrink-0 text-slate-300 group-hover:text-slate-400 transition-colors",
  saveBtnSaved:  "h-7 gap-1.5 text-xs transition-colors bg-emerald-600 hover:bg-emerald-700",
  saveBtnDefault:"h-7 gap-1.5 text-xs transition-colors bg-indigo-600 hover:bg-indigo-700",
}
